version: "3.9"

services:

  # MariaDB service
  wpdbcluster:
    image: mariadb:10.5
    networks:
      - backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ChangeME
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ChangeME
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d

  # WordPress service
  wordpress:
    image: wordpress:5.8
    networks:
      - backend
      - frontend
    ports:
      - 8080:80
    depends_on:
      - wpdbcluster
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      WORDPRESS_DB_HOST: wpdbcluster
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ChangeME
      WORDPRESS_AUTH_KEY: ChangeME
      WORDPRESS_LOGGED_IN_KEY: ChangeME
      WORDPRESS_AUTH_SALT: ChangeME
      WORDPRESS_LOGGED_IN_SALT: ChangeME

  # Nginx service
  nginx:
    image: nginx:1.19
    networks:
      - frontend
      - backend
    environment:
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
    depends_on:
      - php
    labels:
      - traefik.backend=nginx
      - traefik.port=80
      - traefik.frontend.rule=Host:wp.docker.localhost

  # PHP service
  php:
    image: php:7.3-fpm-alpine
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025

  # Varnish service
  varnish:
    image: varnish:6.3
    networks:
      - backend
    depends_on:
      - nginx
    environment:
      VARNISH_SECRET: secret
      VARNISH_BACKEND_HOST: nginx
      VARNISH_BACKEND_PORT: 80
    labels:
      - traefik.backend=varnish
      - traefik.port=6081
      - traefik.frontend.rule=Host:varnish.wp.docker.localhost

  # Redis service
  redis:
    image: redis:7.0
    networks:
      - backend

  # PHPMyAdmin service
  pma:
    image: phpmyadmin/phpmyadmin:5.0
    networks:
      - backend
      - frontend
    environment:
      PMA_HOST: wpdbcluster
      PMA_USER: wordpress
      PMA_PASSWORD: ChangeME
    ports:
      - 8082:80
    labels:
      - traefik.backend=pma
      - traefik.port=80
      - traefik.frontend.rule=Host:pma.wp.docker.localhost
