# Default entrypoints
defaultEntryPoints = ["http", "https"]

# Web interface
[web]
  address = ":8080"

# Entrypoints
[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

# Docker provider configuration
[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "localhost"
  watch = true
  exposedbydefault = false

# Define routers for each service
[frontends]
  [frontends.nginx]
    backend = "nginx"
    passHostHeader = true
    [frontends.nginx.routes.main]
      rule = "Host: wp.docker.localhost"
  [frontends.varnish]
    backend = "varnish"
    passHostHeader = true
    [frontends.varnish.routes.main]
      rule = "Host: varnish.wp.docker.localhost"
  [frontends.pma]
    backend = "pma"
    passHostHeader = true
    [frontends.pma.routes.main]
      rule = "Host: pma.wp.docker.localhost"
  [frontends.mailhog]
    backend = "mailhog"
    passHostHeader = true
    [frontends.mailhog.routes.main]
      rule = "Host: mailhog.wp.docker.localhost"
  [frontends.portainer]
    backend = "portainer"
    passHostHeader = true
    [frontends.portainer.routes.main]
      rule = "Host: portainer.wp.docker.localhost"

# Define backends for each service
[backends]
  [backends.nginx]
    [backends.nginx.servers.server1]
      url = "http://nginx:80"
  [backends.varnish]
    [backends.varnish.servers.server1]
      url = "http://varnish:6081"
  [backends.pma]
    [backends.pma.servers.server1]
      url = "http://pma:80"
  [backends.mailhog]
    [backends.mailhog.servers.server1]
      url = "http://mailhog:8025"
  [backends.portainer]
    [backends.portainer.servers.server1]
      url = "http://portainer:9000"
