[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"
  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true
  insecure = true

[providers]
  [providers.docker]
    swarmMode = true
    exposedByDefault = false

[http]
  [http.routers]
    [http.routers.nginx]
      rule = "Host(`wp.docker.localhost`)"
      service = "nginx"
      entryPoints = ["web", "websecure"]
    [http.routers.varnish]
      rule = "Host(`varnish.wp.docker.localhost`)"
      service = "varnish"
      entryPoints = ["web", "websecure"]
    [http.routers.pma]
      rule = "Host(`pma.wp.docker.localhost`)"
      service = "pma"
      entryPoints = ["web", "websecure"]
    [http.routers.mailhog]
      rule = "Host(`mailhog.wp.docker.localhost`)"
      service = "mailhog"
      entryPoints = ["web", "websecure"]
    [http.routers.portainer]
      rule = "Host(`portainer.wp.docker.localhost`)"
      service = "portainer"
      entryPoints = ["web", "websecure"]

  [http.services]
    [http.services.nginx]
      [http.services.nginx.loadBalancer]
        [[http.services.nginx.loadBalancer.servers]]
          url = "http://nginx:80"
    [http.services.varnish]
      [http.services.varnish.loadBalancer]
        [[http.services.varnish.loadBalancer.servers]]
          url = "http://varnish:6081"
    [http.services.pma]
      [http.services.pma.loadBalancer]
        [[http.services.pma.loadBalancer.servers]]
          url = "http://pma:80"
    [http.services.mailhog]
      [http.services.mailhog.loadBalancer]
        [[http.services.mailhog.loadBalancer.servers]]
          url = "http://mailhog:8025"
    [http.services.portainer]
      [http.services.portainer.loadBalancer]
        [[http.services.portainer.loadBalancer.servers]]
          url = "http://portainer:9000"
