name: End-to-End Tests

on:
  push:
    branches:
      - main

jobs:
  e2e_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: your-dockerhub-username/wordpress:${{ github.sha }}

      - name: Start Docker containers
        run: docker stack deploy -c docker-stack.yml wordpress

      - name: Wait for services to start
        run: |
          echo "Waiting for services to be healthy..."
          sleep 30  # Consider using healthchecks instead

      - name: Test Wordpress
        run: curl --fail --retry 5 --retry-delay 5 http://localhost:8080

      - name: Test Traefik
        run: curl --fail --retry 5 --retry-delay 5 http://localhost:8000

      - name: Stop Docker containers
        run: docker stack rm wordpress
